#!/usr/bin/env node

const request = require('node-fetch');

require('dotenv').config();

const { CLOUDFLARE_KEY, EMAIL } = require('./keychain.json');

const zoneId = process.argv[2]

async function main() {
    const endpoint = `https://api.cloudflare.com/client/v4/zones/${zoneId}/dns_records/`
    const res = await request(endpoint, {
        method: 'get',
        headers: {
            'X-Auth-Key': CLOUDFLARE_KEY,
            'X-Auth-Email': EMAIL,
            'Content-Type': 'application/json'
        }
    })
    
    json = await res.json();
    
    if (!json.success) {
        return console.error(json.errors)
    }
    
    json.result.map(record => {
        const { id, name, type, content } = record
        console.log({
            id, name, type, content
        })
    })
} 

main();
