#!/usr/bin/env node

const request = require('node-fetch');

require('dotenv').config();
const data = require('./data');

const zoneId = process.env.ZONE_ID

if (!data.records || data.records.length < 0) {
    throw new Error('No record IDs given');
}

const ipEndpoint = 'https://api.ipify.org?format=json';

async function main() {
    // Fetch current network IP
    let res = await request(ipEndpoint);
    let json = await res.json();
    let ip = json.ip;
    if (!ip) return console.error('IP not given');

    // Loop through records

    for (const record of data.records) {
        const endpoint = `https://api.cloudflare.com/client/v4/zones/${zoneId}/dns_records/${record.id}`;
        res = await request(endpoint, {
            method: 'put',
            headers: {
                'X-Auth-Key': process.env.CLOUDFLARE_KEY,
                'X-Auth-Email': process.env.EMAIL,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                type: record.type,
                content: ip,
                name: record.domain,
                proxied: record.proxied || true
            })
        });

        json = await res.json();
        console.log(json);
    }
} 

main();
